CREATE SEQUENCE seq_train  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_gate   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_sensor START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_log    START WITH 1 INCREMENT BY 1;